module ex256_umul_csa_androws_4to2_leave4_cla(in, out);
  input [9:0] in;
  output [9:0] out;
  wire [4:0] a = in[4:0];
  wire [4:0] b = in[9:5];
  wire [9:0] row0 = ({10{b[0]}} & {5'b0, a});
  wire [9:0] row1 = ({10{b[1]}} & ({5'b0, a} << 1));
  wire [9:0] row2 = ({10{b[2]}} & ({5'b0, a} << 2));
  wire [9:0] row3 = ({10{b[3]}} & ({5'b0, a} << 3));
  wire [9:0] row4 = ({10{b[4]}} & ({5'b0, a} << 4));
  wire [9:0] ft_temp_s = row0 ^ row1 ^ row2;
  wire [9:0] ft_temp_c = ((row0 & row1) | (row0 & row2) | (row1 & row2)) << 1;
  wire [9:0] ft_s = ft_temp_s ^ ft_temp_c ^ row3;
  wire [9:0] ft_c = ((ft_temp_s & ft_temp_c) | (ft_temp_s & row3) | (ft_temp_c & row3)) << 1;
  wire [9:0] ft2_s = ft_s ^ ft_c ^ row4;
  wire [9:0] ft2_c = ((ft_s & ft_c) | (ft_s & row4) | (ft_c & row4)) << 1;
  wire [9:0] ftcla_p = ft2_s ^ ft2_c;
  wire [9:0] ftcla_g = ft2_s & ft2_c;
  wire [9:0] cla_sum;
  assign cla_sum[0] = ftcla_p[0] ^ 1'b0;
  assign cla_sum[1] = ftcla_p[1] ^ (ftcla_g[0]);
  assign cla_sum[2] = ftcla_p[2] ^ (ftcla_g[1] | (ftcla_p[1] & ftcla_g[0]));
  assign cla_sum[3] = ftcla_p[3] ^ (ftcla_g[2] | (ftcla_p[2] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_g[0]));
  assign cla_sum[4] = ftcla_p[4] ^ (ftcla_g[3] | (ftcla_p[3] & ftcla_g[2]) | (ftcla_p[2] & ftcla_p[3] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_p[3] & ftcla_g[0]));
  assign cla_sum[5] = ftcla_p[5] ^ (ftcla_g[4] | (ftcla_p[4] & ftcla_g[3]) | (ftcla_p[3] & ftcla_p[4] & ftcla_g[2]) | (ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_g[0]));
  assign cla_sum[6] = ftcla_p[6] ^ (ftcla_g[5] | (ftcla_p[5] & ftcla_g[4]) | (ftcla_p[4] & ftcla_p[5] & ftcla_g[3]) | (ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_g[2]) | (ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_g[0]));
  assign cla_sum[7] = ftcla_p[7] ^ (ftcla_g[6] | (ftcla_p[6] & ftcla_g[5]) | (ftcla_p[5] & ftcla_p[6] & ftcla_g[4]) | (ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_g[3]) | (ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_g[2]) | (ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_g[0]));
  assign cla_sum[8] = ftcla_p[8] ^ (ftcla_g[7] | (ftcla_p[7] & ftcla_g[6]) | (ftcla_p[6] & ftcla_p[7] & ftcla_g[5]) | (ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_g[4]) | (ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_g[3]) | (ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_g[2]) | (ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_g[0]));
  assign cla_sum[9] = ftcla_p[9] ^ (ftcla_g[8] | (ftcla_p[8] & ftcla_g[7]) | (ftcla_p[7] & ftcla_p[8] & ftcla_g[6]) | (ftcla_p[6] & ftcla_p[7] & ftcla_p[8] & ftcla_g[5]) | (ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_p[8] & ftcla_g[4]) | (ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_p[8] & ftcla_g[3]) | (ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_p[8] & ftcla_g[2]) | (ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_p[8] & ftcla_g[1]) | (ftcla_p[1] & ftcla_p[2] & ftcla_p[3] & ftcla_p[4] & ftcla_p[5] & ftcla_p[6] & ftcla_p[7] & ftcla_p[8] & ftcla_g[0]));
  assign out = cla_sum;
endmodule
